[package]
name = "example"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
# license = ""           # e.g., "MIT", "GPL", "Apache 2.0"
# authors = ["..."]      # e.g., ["Joe Smith (joesmith@noemail.com)", "John Snow (johnsnow@noemail.com)"]

[dependencies]

# For remote import, use the `{ git = "...", subdir = "...", rev = "..." }`.
# Revision can be a branch, a tag, and a commit hash.
# MyRemotePackage = { git = "https://some.remote/host.git", subdir = "remote/path", rev = "main" }

# For local dependencies use `local = path`. Path is relative to the package root
Launchpad = { local = "../contract" }

# To resolve a version conflict and force a specific version for dependency
# override use `override = true`
# Override = { local = "../conflicting/version", override = true }

#Upgradecap 0xf0442f30b977435a3ec2668193f8365eeae478285b196fac8a829f72526cfd2a
# MintCap 0xb4ac2714b87f7ca5d2a026b2a95b52bddcad586cccf861ecc45e472db16cac24
# TransferPolicy 0x97be3aeb5e91401459bede5b0b4879067692e7ffb89ea616f7deda6d744e6b95
# TransferPolicyCap 0x0bbc06f139b1e26be25e7229f61c91d81a1d5d643a05f07ce2420b40e78fd0b9
# Publisher 0x8eaccdb1481e76546f07697692982c33eccd49420106da0c9be18f84e581f760
# Config 0x01f4fc06ac9a9edd98d45ac4bc2618e7741bb09993d84aae381f432dee0d026a
# 
[addresses]
example = "0x13bf486069f8cc11d636d666612ac2180dd6e86bbea593f429505bddd6b1bc97"

# Named addresses will be accessible in Move as `@name`. They're also exported:
# for example, `std = "0x1"` is exported by the Standard Library.
# alice = "0xA11CE"

[dev-dependencies]
# The dev-dependencies section allows overriding dependencies for `--test` and
# `--dev` modes. You can introduce test-only dependencies here.
# Local = { local = "../path/to/dev-build" }

[dev-addresses]
# The dev-addresses section allows overwriting named addresses for the `--test`
# and `--dev` modes.
# alice = "0xB0B"

